---
author: Kaitlyn Steck
title: Graduate Assistant
format:
  classic-cv-pdf: default
cvcolor: 58748F #without `#`
cvfont: raleway #texlive fonts like raleway,fetamont,gillius,comfortaa
cvmeta:
    left:   616-206-6603
    right: ksteck2@huskers.unl.edu
execute:
  echo: false
---

```{r}
#| label: cvevents
cvevents <- function(tbl, when, what, where, details) {

    command_start <- "\\cvevent"

    res <- paste0(
        command_start, "{", tbl[[when]], "}", 
        "{", tbl[[what]], "}",
        "{", tbl[[where]], "}")
    
    tbl[[details]] <- sapply(tbl[[details]], function(x) paste0("{", x, "}", collapse = ","))
    res <- paste0(res, "{",tbl[[details]],"}")

    cat(res, sep = "\n")
}

cvdetails<- function(tbl, details) {
  res <- sapply(tbl[[details]], function(x) paste0(x, collapse = ","))
   cat(res, sep = "\n\n | \n\n")
}
```

# Education

```{r }
#| label: education
#| output: asis
tibble::tribble(
    ~degree, ~uni, ~loc, ~dates, ~details,
    "Doctor of Philosophy- Psychology: Neuroscience and Behavior", "University of Nebraska- Lincoln","Lincoln, Nebraska", "August 2024 - Present", c("Advisor: Dr. Rick Bevins"),
    "Master of Arts- Psychology: Behavior Analysis", "Western Michigan University","Kalamazoo, Michigan", "Aug 2022 - April 2024", c("Advisor: Dr. Lisa Baker", "Thesis: Evaluation of a Dietary Probiotic Supplement on
Methamphetamine-Induced Impulsive Action in Rats Maintained on a Differential
Reinforcement of Low Rate Schedule"),
     "Bachelor of Science- Psychology: Behavioral Science",  "Western Michigan University","Kalamazoo, Michigan", "Aug 2019 - April 2022", c("Minor: Data Analysis"),
) |>
    cvevents(when = "dates", what = "degree", where = "loc", details = "details")
```

# Publications

```{r}
#| label: publications
#| output: asis
tibble::tribble(
     ~details,
    "Barrett S.T., McNealy K.R., Knabel, M.L., Burrichter, R.M., Steck, K.A., & Bevins R.A (2025). The Inside Story: Interoceptive Pavlovian Conditioning with the Nicotine Stimulus. Journal of Experimental Psychology: Animal Learning and Cognition.",
) |>
    cvdetails(details = "details")
```

# 

# Presentations

```{r}
#| label: presentations
#| output: asis
tibble::tribble(
     ~details,
    "Steck, K.A., McNealy, K.R., Ramirez, H., Flynn, A., Knabel, M.L., Smyth, S., Barrett, S.T.,
Bevins, R.A. (2024). Amplification of the conditioned reinforcing value of the nicotine stimulus
is sensitive to the temporal contiguity between the nicotine CS and sucrose US. 2024
Symposium on Substance Use Research | Rural Drug Addiction Research Center.",
    
    "McNealy, K.R., Steck, K.A., Ramirez, H., Flynn, A., Knabel, M.L., Smyth, S., Barrett, S.T.,
Bevins, R.A. (2024). Amplification of the conditioned reinforcing value of the nicotine stimulus
is sensitive to the temporal contiguity between the nicotine CS and sucrose US. Pavlovian
Society, Indianapolis, Indiana.",
    
    "Brabant, P.D., Steck, K.A., Baker, L.E. (2024). Evaluation of a Dietary Probiotic Supplement on
Methamphetamine-Induced Impulsive Action in Rats Maintained on a Differential
Reinforcement of Low Rate Schedule. Michigan Society for Neuroscience Annual Meeting, Ann
Arbor, Michigan.",
    
  "Steck, K.A. and Baker, L.E. (2024). Pro-impulsive Effects of 1-(1-benzofuran-5-yl)-2-
(methylamino) propan-1-one (BK-5-MAPB) Enantiomers in Rats. Michigan Society for
Neuroscience Annual Meeting, Ann Arbor, Michigan.",
  
  "Steck, K.A. and Baker, L.E. (2024). Evaluation of a Dietary Probiotic Supplement on
Methamphetamine-Induced Impulsive Action in Rats Maintained on a Differential
Reinforcement of Low Rate Schedule. Graduate Student Research Day, Western Michigan
University, Kalamazoo, Michigan.",
    
) |>
    cvdetails(details = "details")
```

# 
